import express from 'express'
import Razorpay from 'razorpay'
import Cart from '../models/Cart.js'
import Order from '../models/Order.js'
import authMiddleware from '../middleware/authMiddleware.js'
import crypto from 'crypto'
import Product from '../models/Product.js'
import mongoose from 'mongoose'
import dotenv from "dotenv"
dotenv.config()
const router = express.Router();



router.post("/payment/create-order", authMiddleware, async (req, res) => {
    try {
        const razorpayInstance = new Razorpay({
            key_id: process.env.RAZORPAY_KEY_ID,
            key_secret: process.env.RAZORPAY_KEY_SECRET
        });
        // const { currency, receipt } = req.body;
        // if (!currency || !receipt) {
        //     return res.status(400).json({ message: "Missing required fields" })
        // }
        const { shippingAddress } = req.body;
        if (!shippingAddress) return res.status(400).json({ message: "missing required fields" });
        const userId = req.user.id;
        const cart = await Cart.findOne({ user: userId });
        if (!cart) {
            return res.status(404).json({ message: "Cart not found" });
        }
        if (cart.cartItems.length === 0) return res.status(400).json({ message: "cart is empty" });

        const totalPrice = cart.totalPrice;
        const newOrder = await Order.create({
            user: userId,
            orderItems: cart.cartItems,
            totalPrice: totalPrice,
            shippingAddress: shippingAddress
        })
        const totalAmount = cart.totalPrice * 100;
        const options = {
            amount: totalAmount,
            currency: "INR",
            receipt: "receipt_" + Date.now()
        };

        const razorpayOrder = await razorpayInstance.orders.create(options);
        if (!razorpayOrder) return res.status(500).json({ message: "failed to create order" });

        newOrder.razorpayOrderId = razorpayOrder.id;
        await newOrder.save();

        return res.status(200).json({ message: "order place successfully", razorpayOrder });

    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

router.post("/payment/verify", authMiddleware, async (req, res) => {
    const session = await mongoose.startSession();//We use MongoDB sessions to ensure atomic transactions, so multiple database operations either all succeed or all roll back together, maintaining data consistency.
    session.startTransaction();
    try {
        const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;//razorpay_payment_id and razorpay_signature are automatically generated by razorpay and given to frontend.
        const userId = req.user.id;
        const order = await Order.findOne({ razorpayOrderId: razorpay_order_id }).session(session);
        if (!order) throw new Error("order not found");
        if (order.user.toString() !== userId.toString()) {
            throw new Error("Unauthorized");
        }
        if (order.paymentStatus === 'paid') {
            throw new Error("Payment is already done");
        }
        const expected_signature = crypto
            .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
            .update(razorpay_order_id + '|' + razorpay_payment_id)
            .digest('hex');// expected_signature is the signature generated by our backend server using razorpay_order_id and razorpay_payment_id and razorpay_key_secret.we compare this with the signature sent by razorpay to verify the payment.
        if (expected_signature !== razorpay_signature) {
            throw new Error("Invalid signature");
        }
        order.paymentStatus = "paid";
        order.razorpayPaymentId = razorpay_payment_id;
        for (const item of order.orderItems) {
            const product = await Product.findById(item.product).session(session);
            if (!product) throw new Error("Product not found");
            if (product.stock < item.quantity) throw new Error("Insufficient stock");
            product.stock -= item.quantity;
            await product.save({ session });
        }
        await Cart.deleteOne({ user: userId }).session(session);
        await order.save({ session });
        await session.commitTransaction();
        return res.status(200).json({ message: "Payment verified successfully" });
    } catch (error) {
        await session.abortTransaction();
        res.status(500).json({ message: error.message });
    } finally {
        await session.endSession();
    }

})

export default router;
